services:
  dtek_bot:
    build:
      context: ../..
      dockerfile: dtek/bot/Dockerfile
    container_name: dtek_bot
    restart: unless-stopped
    env_file:
      - ../../.env
    environment:
      - DTEK_BOT_TOKEN=${DTEK_BOT_TOKEN}
      - DTEK_DB_PATH=/data/dtek_bot.db
      - DTEK_FONT_PATH=/app/resources/DejaVuSans.ttf
    volumes:
      - ../../dtek/data:/data
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
