services:
  dtek_bot:
    build:
      context: ../..
      dockerfile: dtek/bot/Dockerfile
    container_name: dtek_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/data/bot.db
      - FONT_PATH=/app/resources/DejaVuSans.ttf
    volumes:
      - ../../dtek/data:/data
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
