services:
  cek_bot:
    build:
      context: ../..
      dockerfile: cek/bot/Dockerfile
    container_name: cek_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_PATH=/data/bot.db
      - FONT_PATH=/app/resources/DejaVuSans.ttf
    volumes:
      - ../../cek/data:/data
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
